using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ProjectEuler.Puzzles.Puzzles
{
    public class Puzzle002 : IPuzzle
    {
        public string Title => "Even Fibonacci numbers";
        public string Summary => "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:" + Environment.NewLine
                                    +"1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..." + Environment.NewLine
                                +"By considering the terms in the Fibonacci sequence whose "
                                + "values do not exceed four million, find the sum of the even-valued terms.";
        public string Answer { get; private set; }
        public void SolvePuzzle()
        {
            var fibonaccisequence = GetFibonacciSequenceUntil(4000000);
            var sumOfEvenValuedTerms = fibonaccisequence.Where(x => x % 2 == 0).Sum();
            Answer = sumOfEvenValuedTerms.ToString();
        }

        private IList<int> GetFibonacciSequenceUntil(int max)
        {
            IList<int> fibonacciValues = new List<int>() { 1, 2};
            var n = 0;
            while (true)
            {
                var newValue = fibonacciValues[n] + fibonacciValues[n + 1];
                if (newValue > max)
                    break;

                fibonacciValues.Add(newValue);
                n++;
            }
            return fibonacciValues;
        }
    }
}
